language: java

jdk:
  - oraclejdk8

script: ./gradlew check jacocoTestReport

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Kotlin -r build/reports/jacoco/test/jacocoTestReport.xml

before_deploy:
  - ./gradlew publishMavenJavaPublicationToMavenRepository

deploy:
  provider: bintray
  file: bintray.json
  user: adrien-ben
  key:
    secure: AN1rB4vnLjquByIK/58lQvIGbFEbMumw46Rg7Elbuhn9zawasSg7otHER292Xw91gDXhn7fiS0ND3zcJ7nrV1kr5He1Z1C1++lXMwtWCKg+B1U6KMCboU4LqNs9LNqqoI3/CKyVyxNnhDtSWm2y3/KZ6B4bA7KlTR90PpLFhFSHFhqOOyLzBAQK2A+6nGBvPtDT9k/s9YhATQaPdInqMuKm6dmzdb64VLd83nP40U3kbPSaWSett38kM75zGFeXVZqqpGiOCyKhqnSkhJkUxAREDwibCNO2cSZSEsgUmPYshxFOnNQRhR7TZjWhkLjxVnCeKgxC0epfo0LQ1HP56Nn9XLXcaaqbjcX3xMgMe4ByP78Z8t17TlVrb2hMuxkl7zkbt2yJ8fTkxRnwe2B+66MK/GFO9s3573qSy0W13sMV8QPDiSL+xgEKFsC/aOG3iBvTCqlUpAm4Y/FqNKbVjKIIEepqeDnZRN3wvF7lP5WeRySBrfq6O6f3vPG9xf30QBDy00GVFyxpyk6p41mqr3kcVmyxDKQjyWFSS6lkKRIidKgcoZpvVUiIuj29WuCu+wajlvKUXBKSDi0u/4ezTSGM1Dw8jd91xB4uTXx1xvyLkCrE2GqI55bow9NIHKghGXGWxa36Q2yqGca0oRSrkJGXkcE1NMokpcIemcvkjRzE=
  skip_cleanup: true
